#include <iostream>
#include <chrono>
#include <znn/interface/conv_wrapper.hpp>
#include "znet.hpp"


znn::phi::Znet::Znet(void)
{
	tensors["conv0_d1"] = new znn::phi::hbw_array<float>(5308416);
	tensors["conv0_d0"] = new znn::phi::hbw_array<float>(15925248);
	tensors["conv0_d3"] = new znn::phi::hbw_array<float>(663552);
	tensors["conv0_d2"] = new znn::phi::hbw_array<float>(1990656);
	tensors["conv0_d5"] = new znn::phi::hbw_array<float>(62208);
	tensors["conv0_d4"] = new znn::phi::hbw_array<float>(207360);
	tensors["conv4_d3"] = new znn::phi::hbw_array<float>(663552);
	tensors["conv4_d4"] = new znn::phi::hbw_array<float>(207360);
	tensors["conv4_d0"] = new znn::phi::hbw_array<float>(15925248);
	tensors["sum4_d2"] = new znn::phi::hbw_array<float>(1990656);
	tensors["Deconvolution4"] = new znn::phi::hbw_array<float>(5308416);
	tensors["conv4_d1"] = new znn::phi::hbw_array<float>(5308416);
	tensors["convf1_d3"] = new znn::phi::hbw_array<float>(663552);
	tensors["convf1_d2"] = new znn::phi::hbw_array<float>(1990656);
	tensors["convf1_d5"] = new znn::phi::hbw_array<float>(62208);
	tensors["convf1_d4"] = new znn::phi::hbw_array<float>(207360);
	tensors["Eltwise4"] = new znn::phi::hbw_array<float>(5308416);
	tensors["convf2_d4"] = new znn::phi::hbw_array<float>(207360);
	tensors["convf2_d5"] = new znn::phi::hbw_array<float>(62208);
	tensors["convf6_d2"] = new znn::phi::hbw_array<float>(1990656);
	tensors["Deconvolution2"] = new znn::phi::hbw_array<float>(663552);
	tensors["convf6_d4"] = new znn::phi::hbw_array<float>(207360);
	tensors["convf2_d2"] = new znn::phi::hbw_array<float>(1990656);
	tensors["convf2_d3"] = new znn::phi::hbw_array<float>(663552);
	tensors["sum0_d5"] = new znn::phi::hbw_array<float>(62208);
	tensors["sum0_d4"] = new znn::phi::hbw_array<float>(207360);
	tensors["conv4_d2"] = new znn::phi::hbw_array<float>(1990656);
	tensors["sum0_d1"] = new znn::phi::hbw_array<float>(5308416);
	tensors["sum0_d0"] = new znn::phi::hbw_array<float>(15925248);
	tensors["sum0_d3"] = new znn::phi::hbw_array<float>(663552);
	tensors["sum0_d2"] = new znn::phi::hbw_array<float>(1990656);
	tensors["convf5_d4"] = new znn::phi::hbw_array<float>(207360);
	tensors["score"] = new znn::phi::hbw_array<float>(0);
	tensors["Deconvolution3"] = new znn::phi::hbw_array<float>(1990656);
	tensors["convf5_d3"] = new znn::phi::hbw_array<float>(663552);
	tensors["convf5_d2"] = new znn::phi::hbw_array<float>(1990656);
	tensors["input"] = new znn::phi::hbw_array<float>(0);
	tensors["conv2_d5"] = new znn::phi::hbw_array<float>(62208);
	tensors["conv2_d4"] = new znn::phi::hbw_array<float>(207360);
	tensors["conv2_d3"] = new znn::phi::hbw_array<float>(663552);
	tensors["conv2_d2"] = new znn::phi::hbw_array<float>(1990656);
	tensors["conv2_d1"] = new znn::phi::hbw_array<float>(5308416);
	tensors["conv2_d0"] = new znn::phi::hbw_array<float>(15925248);
	tensors["conv6_d3"] = new znn::phi::hbw_array<float>(663552);
	tensors["conv6_d2"] = new znn::phi::hbw_array<float>(1990656);
	tensors["sum4_d3"] = new znn::phi::hbw_array<float>(663552);
	tensors["conv6_d0"] = new znn::phi::hbw_array<float>(15925248);
	tensors["convf6_d3"] = new znn::phi::hbw_array<float>(663552);
	tensors["deconv_d3"] = new znn::phi::hbw_array<float>(15925248);
	tensors["conv5_d2"] = new znn::phi::hbw_array<float>(1990656);
	tensors["conv5_d3"] = new znn::phi::hbw_array<float>(663552);
	tensors["conv5_d0"] = new znn::phi::hbw_array<float>(15925248);
	tensors["conv5_d1"] = new znn::phi::hbw_array<float>(5308416);
	tensors["Deconvolution1"] = new znn::phi::hbw_array<float>(207360);
	tensors["conv5_d4"] = new znn::phi::hbw_array<float>(207360);
	tensors["sum4_d4"] = new znn::phi::hbw_array<float>(207360);
	tensors["sum4_d1"] = new znn::phi::hbw_array<float>(5308416);
	tensors["sum4_d0"] = new znn::phi::hbw_array<float>(15925248);
	tensors["conv1_d4"] = new znn::phi::hbw_array<float>(207360);
	tensors["conv1_d5"] = new znn::phi::hbw_array<float>(62208);
	tensors["conv1_d2"] = new znn::phi::hbw_array<float>(1990656);
	tensors["conv1_d3"] = new znn::phi::hbw_array<float>(663552);
	tensors["conv1_d0"] = new znn::phi::hbw_array<float>(15925248);
	tensors["conv1_d1"] = new znn::phi::hbw_array<float>(5308416);
	tensors["convi"] = new znn::phi::hbw_array<float>(15925248);
	tensors["conv6_d4"] = new znn::phi::hbw_array<float>(207360);
	tensors["Eltwise3"] = new znn::phi::hbw_array<float>(1990656);
	tensors["Eltwise2"] = new znn::phi::hbw_array<float>(663552);
	tensors["Eltwise1"] = new znn::phi::hbw_array<float>(207360);
	tensors["pool_d2"] = new znn::phi::hbw_array<float>(1327104);
	tensors["pool_d3"] = new znn::phi::hbw_array<float>(497664);
	tensors["pool_d1"] = new znn::phi::hbw_array<float>(3981312);
	tensors["pool_d4"] = new znn::phi::hbw_array<float>(165888);
	tensors["pool_d5"] = new znn::phi::hbw_array<float>(51840);
	tensors["conv7_d0"] = new znn::phi::hbw_array<float>(15925248);
	tensors["output"] = new znn::phi::hbw_array<float>(0);
	tensors["merge_d3"] = new znn::phi::hbw_array<float>(15925248);
	tensors["conv6_d1"] = new znn::phi::hbw_array<float>(5308416);
	
	weights["conv0_d1_kernel"] = new znn::phi::hbw_array<float>(7776);
	weights["conv0_d1_bias"] = new znn::phi::hbw_array<float>(36);
	weights["conv0_d0_kernel"] = new znn::phi::hbw_array<float>(6048);
	weights["conv0_d0_bias"] = new znn::phi::hbw_array<float>(28);
	weights["conv0_d3_kernel"] = new znn::phi::hbw_array<float>(27648);
	weights["conv0_d3_bias"] = new znn::phi::hbw_array<float>(64);
	weights["conv0_d2_kernel"] = new znn::phi::hbw_array<float>(13824);
	weights["conv0_d2_bias"] = new znn::phi::hbw_array<float>(48);
	weights["conv0_d5_kernel"] = new znn::phi::hbw_array<float>(69120);
	weights["conv0_d5_bias"] = new znn::phi::hbw_array<float>(96);
	weights["conv0_d4_kernel"] = new znn::phi::hbw_array<float>(46080);
	weights["conv0_d4_bias"] = new znn::phi::hbw_array<float>(80);
	weights["conv4_d3_kernel"] = new znn::phi::hbw_array<float>(36864);
	weights["conv4_d3_bias"] = new znn::phi::hbw_array<float>(64);
	weights["conv4_d4_kernel"] = new znn::phi::hbw_array<float>(57600);
	weights["conv4_d4_bias"] = new znn::phi::hbw_array<float>(80);
	weights["conv4_d1_kernel"] = new znn::phi::hbw_array<float>(10368);
	weights["conv4_d1_bias"] = new znn::phi::hbw_array<float>(36);
	weights["conv5_d0_kernel"] = new znn::phi::hbw_array<float>(6048);
	weights["conv5_d0_bias"] = new znn::phi::hbw_array<float>(28);
	weights["conv4_d0_kernel"] = new znn::phi::hbw_array<float>(6048);
	weights["conv4_d0_bias"] = new znn::phi::hbw_array<float>(28);
	weights["conv6_d3_kernel"] = new znn::phi::hbw_array<float>(12288);
	weights["conv6_d3_bias"] = new znn::phi::hbw_array<float>(64);
	weights["conv6_d2_kernel"] = new znn::phi::hbw_array<float>(6912);
	weights["conv6_d2_bias"] = new znn::phi::hbw_array<float>(48);
	weights["convf6_d2_kernel"] = new znn::phi::hbw_array<float>(20736);
	weights["convf6_d2_bias"] = new znn::phi::hbw_array<float>(48);
	weights["convf6_d4_kernel"] = new znn::phi::hbw_array<float>(57600);
	weights["convf6_d4_bias"] = new znn::phi::hbw_array<float>(80);
	weights["conv6_d4_kernel"] = new znn::phi::hbw_array<float>(19200);
	weights["conv6_d4_bias"] = new znn::phi::hbw_array<float>(80);
	weights["convf5_d4_kernel"] = new znn::phi::hbw_array<float>(57600);
	weights["convf5_d4_bias"] = new znn::phi::hbw_array<float>(80);
	weights["convf5_d3_kernel"] = new znn::phi::hbw_array<float>(36864);
	weights["convf5_d3_bias"] = new znn::phi::hbw_array<float>(64);
	weights["convf5_d2_kernel"] = new znn::phi::hbw_array<float>(20736);
	weights["convf5_d2_bias"] = new znn::phi::hbw_array<float>(48);
	weights["Deconvolution2_kernel"] = new znn::phi::hbw_array<float>(20480);
	weights["Deconvolution2_bias"] = new znn::phi::hbw_array<float>(64);
	weights["Deconvolution4_kernel"] = new znn::phi::hbw_array<float>(6912);
	weights["Deconvolution4_bias"] = new znn::phi::hbw_array<float>(36);
	weights["Deconvolution1_kernel"] = new znn::phi::hbw_array<float>(30720);
	weights["Deconvolution1_bias"] = new znn::phi::hbw_array<float>(80);
	weights["conv2_d5_kernel"] = new znn::phi::hbw_array<float>(27648);
	weights["conv2_d5_bias"] = new znn::phi::hbw_array<float>(96);
	weights["Deconvolution3_kernel"] = new znn::phi::hbw_array<float>(12288);
	weights["Deconvolution3_bias"] = new znn::phi::hbw_array<float>(48);
	weights["conv2_d3_kernel"] = new znn::phi::hbw_array<float>(12288);
	weights["conv2_d3_bias"] = new znn::phi::hbw_array<float>(64);
	weights["conv2_d1_kernel"] = new znn::phi::hbw_array<float>(10368);
	weights["conv2_d1_bias"] = new znn::phi::hbw_array<float>(36);
	weights["score_kernel"] = new znn::phi::hbw_array<float>(1800);
	weights["score_bias"] = new znn::phi::hbw_array<float>(3);
	weights["conv4_d2_kernel"] = new znn::phi::hbw_array<float>(20736);
	weights["conv4_d2_bias"] = new znn::phi::hbw_array<float>(48);
	weights["conv6_d1_kernel"] = new znn::phi::hbw_array<float>(10368);
	weights["conv6_d1_bias"] = new znn::phi::hbw_array<float>(36);
	weights["convf6_d3_kernel"] = new znn::phi::hbw_array<float>(36864);
	weights["convf6_d3_bias"] = new znn::phi::hbw_array<float>(64);
	weights["conv6_d0_kernel"] = new znn::phi::hbw_array<float>(6048);
	weights["conv6_d0_bias"] = new znn::phi::hbw_array<float>(28);
	weights["deconv_d3_kernel"] = new znn::phi::hbw_array<float>(3584);
	weights["deconv_d3_bias"] = new znn::phi::hbw_array<float>(28);
	weights["conv5_d2_kernel"] = new znn::phi::hbw_array<float>(6912);
	weights["conv5_d2_bias"] = new znn::phi::hbw_array<float>(48);
	weights["conv5_d3_kernel"] = new znn::phi::hbw_array<float>(12288);
	weights["conv5_d3_bias"] = new znn::phi::hbw_array<float>(64);
	weights["conv5_d1_kernel"] = new znn::phi::hbw_array<float>(10368);
	weights["conv5_d1_bias"] = new znn::phi::hbw_array<float>(36);
	weights["conv5_d4_kernel"] = new znn::phi::hbw_array<float>(19200);
	weights["conv5_d4_bias"] = new znn::phi::hbw_array<float>(80);
	weights["conv1_d4_kernel"] = new znn::phi::hbw_array<float>(19200);
	weights["conv1_d4_bias"] = new znn::phi::hbw_array<float>(80);
	weights["conv1_d5_kernel"] = new znn::phi::hbw_array<float>(27648);
	weights["conv1_d5_bias"] = new znn::phi::hbw_array<float>(96);
	weights["conv1_d2_kernel"] = new znn::phi::hbw_array<float>(6912);
	weights["conv1_d2_bias"] = new znn::phi::hbw_array<float>(48);
	weights["conv1_d3_kernel"] = new znn::phi::hbw_array<float>(12288);
	weights["conv1_d3_bias"] = new znn::phi::hbw_array<float>(64);
	weights["conv1_d0_kernel"] = new znn::phi::hbw_array<float>(6048);
	weights["conv1_d0_bias"] = new znn::phi::hbw_array<float>(28);
	weights["conv1_d1_kernel"] = new znn::phi::hbw_array<float>(10368);
	weights["conv1_d1_bias"] = new znn::phi::hbw_array<float>(36);
	weights["convi_kernel"] = new znn::phi::hbw_array<float>(0);
	weights["convi_bias"] = new znn::phi::hbw_array<float>(28);
	weights["conv7_d0_kernel"] = new znn::phi::hbw_array<float>(6048);
	weights["conv7_d0_bias"] = new znn::phi::hbw_array<float>(28);
	weights["convf1_d3_kernel"] = new znn::phi::hbw_array<float>(36864);
	weights["convf1_d3_bias"] = new znn::phi::hbw_array<float>(64);
	weights["convf1_d2_kernel"] = new znn::phi::hbw_array<float>(20736);
	weights["convf1_d2_bias"] = new znn::phi::hbw_array<float>(48);
	weights["convf1_d5_kernel"] = new znn::phi::hbw_array<float>(82944);
	weights["convf1_d5_bias"] = new znn::phi::hbw_array<float>(96);
	weights["convf1_d4_kernel"] = new znn::phi::hbw_array<float>(57600);
	weights["convf1_d4_bias"] = new znn::phi::hbw_array<float>(80);
	weights["convf2_d4_kernel"] = new znn::phi::hbw_array<float>(57600);
	weights["convf2_d4_bias"] = new znn::phi::hbw_array<float>(80);
	weights["convf2_d5_kernel"] = new znn::phi::hbw_array<float>(82944);
	weights["convf2_d5_bias"] = new znn::phi::hbw_array<float>(96);
	weights["convf2_d2_kernel"] = new znn::phi::hbw_array<float>(20736);
	weights["convf2_d2_bias"] = new znn::phi::hbw_array<float>(48);
	weights["convf2_d3_kernel"] = new znn::phi::hbw_array<float>(36864);
	weights["convf2_d3_bias"] = new znn::phi::hbw_array<float>(64);
	weights["conv2_d4_kernel"] = new znn::phi::hbw_array<float>(19200);
	weights["conv2_d4_bias"] = new znn::phi::hbw_array<float>(80);
	weights["conv2_d2_kernel"] = new znn::phi::hbw_array<float>(6912);
	weights["conv2_d2_bias"] = new znn::phi::hbw_array<float>(48);
	weights["conv2_d0_kernel"] = new znn::phi::hbw_array<float>(6048);
	weights["conv2_d0_bias"] = new znn::phi::hbw_array<float>(28);
	
	
	layers.push_back(new znn::phi::ConvWrapper);
	layers.push_back(new znn::phi::ConvWrapper);
	layers.push_back(new znn::phi::ConvWrapper);
	layers.push_back(new znn::phi::ConvWrapper);
	layers.push_back(new znn::phi::ConvWrapper);
	layers.push_back(new znn::phi::ConvWrapper);
	layers.push_back(new znn::phi::ConvWrapper);
	layers.push_back(new znn::phi::ConvWrapper);
	layers.push_back(new znn::phi::ConvWrapper);
	layers.push_back(new znn::phi::ConvWrapper);
	layers.push_back(new znn::phi::ConvWrapper);
	layers.push_back(new znn::phi::ConvWrapper);
	layers.push_back(new znn::phi::ConvWrapper);
	layers.push_back(new znn::phi::ConvWrapper);
	layers.push_back(new znn::phi::ConvWrapper);
	layers.push_back(new znn::phi::ConvWrapper);
	layers.push_back(new znn::phi::ConvWrapper);
	layers.push_back(new znn::phi::ConvWrapper);
	layers.push_back(new znn::phi::ConvWrapper);
	layers.push_back(new znn::phi::ConvWrapper);
	layers.push_back(new znn::phi::ConvWrapper);
	layers.push_back(new znn::phi::ConvWrapper);
	layers.push_back(new znn::phi::ConvWrapper);
	layers.push_back(new znn::phi::ConvWrapper);
	layers.push_back(new znn::phi::ConvWrapper);
	layers.push_back(new znn::phi::ConvWrapper);
	layers.push_back(new znn::phi::ConvWrapper);
	layers.push_back(new znn::phi::ConvWrapper);
	layers.push_back(new znn::phi::ConvWrapper);
	layers.push_back(new znn::phi::ConvWrapper);
	layers.push_back(new znn::phi::ConvWrapper);
	layers.push_back(new znn::phi::ConvWrapper);
	layers.push_back(new znn::phi::ConvWrapper);
	layers.push_back(new znn::phi::ConvWrapper);
	layers.push_back(new znn::phi::ConvWrapper);
	layers.push_back(new znn::phi::ConvWrapper);
	layers.push_back(new znn::phi::ConvWrapper);
	layers.push_back(new znn::phi::ConvWrapper);
	layers.push_back(new znn::phi::ConvWrapper);
	layers.push_back(new znn::phi::ConvWrapper);
	layers.push_back(new znn::phi::ConvWrapper);
	layers.push_back(new znn::phi::ConvWrapper);
	layers.push_back(new znn::phi::ConvWrapper);
	layers.push_back(new znn::phi::ConvWrapper);
	layers.push_back(new znn::phi::ConvWrapper);
	layers.push_back(new znn::phi::ConvWrapper);
	layers.push_back(new znn::phi::ConvWrapper);
	layers.push_back(new znn::phi::ConvWrapper);
	layers.push_back(new znn::phi::ConvWrapper);
	
	
}


void znn::phi::Znet::forward(void)
{
}

